storage:
  sqlite:
    file: core.db

features:
  wither-sound:
    enabled: true
    debug: false
  tokens:
    enabled: true

tokens:
  claim-until-day: 7
  excluded-worlds: []
  ranks:
    vip:
      permission: tokens.vip
      amount: 3
    legend:
      permission: tokens.legend
      amount: 5